#Site Settings
title: "Learning Designer? Trainer & Assessor"
description: "Designing engaging learning experiences and empowering knowledge through innovation."
theme: minima

# Navigation Menu
header_pages:
  - index.md
  - About_me.md
  - projects.md
  - vet-teaching.md

# Footer / Social Links
social_links:
  github: "your-github-username"
  linkedin: "your-linkedin-profile"
  email: "Marieg0209@gmail.com"
  # Download a copy of my resume (link-to-your-pdf-file.pdf)📄

# Plugins

plugins:
  - jekyll-feed

# Build Settings
markdown: kramdown
highlighter: rouge
